import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "@/components/NavBar";
import { Outfit } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const outFit = Outfit({ subsets: ["latin"], weight: ["300","400", "500", "600", "700"]});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outFit.className}>
        <Providers>
          <NavBar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
